core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('chat/<int:user2_pk>/', views.ChatView.as_view(), name='chat'),
]

django_channels_chatapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Chat url
    path('', include('core.urls')),
    # Auth url
    path('user/', include('user.urls'))
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'user'

urlpatterns = [
    path('login/', 
        auth_views.LoginView.as_view(
            template_name='user/login.html',
            redirect_authenticated_user=True
        ),
        name='login'
    ),
    path('logout/', 
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path('register', views.RegisterView.as_view(), name='register')
]

core/models.py
from uuid import uuid4
from secrets import token_hex

from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

class SenderModel(models.Model):
    '''Model for the sender of chat'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.get_username()
    
class ReceiverModel(models.Model):
    '''Model for the receiver of chat'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.get_username()

class ChatModel(models.Model):
    '''Model for chat'''
    sender = models.ForeignKey(SenderModel, on_delete=models.CASCADE)
    receiver = models.ForeignKey(ReceiverModel, on_delete=models.CASCADE)
    text = models.TextField()
    log = models.DateTimeField(default=now)

    def __str__(self):
        return f'{self.sender.user.get_username()} chats {self.receiver.user.get_username()}'
    
class ChatKeyModel(models.Model):
    '''Contains the chat key that will be used for group name on channel layer'''
    key = models.UUIDField(default=uuid4)
    usernames = models.JSONField(default=list)

    def __str__(self):
        text = 'Users: '
        for count, username in enumerate(self.usernames):
            text += username + ', '
        # Return without ', ' at last
        return text[:len(text) - 2]
    
    @classmethod
    def get_by_usernames(cls, usernames):
        chatkeys = cls.objects.all()
        usernames.sort()
        for chatkey in chatkeys:
            chatkey.usernames.sort()
            if chatkey.usernames == usernames:
                return chatkey

core/views.py
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.shortcuts import render
from django.contrib.auth.models import User

from .models import SenderModel, ReceiverModel, ChatModel

class HomeView(LoginRequiredMixin, View):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        # Add all the users to context even the current authenticated user
        context = {
            'users': User.objects.all()
        }
        return render(request, 'core/home.html', context)

class ChatView(LoginRequiredMixin, View):
    http_method_names = ['get']

    def get(self, request, user2_pk, *args, **kwargs):
        # Setup the user1 and user2
        user1 = User.objects.get(pk=request.user.pk)
        user2 = User.objects.get(pk=user2_pk)

        # Setup sender and receiver models
        user1_sender = SenderModel.objects.get(pk=user1.sendermodel.pk)
        user2_sender = SenderModel.objects.get(pk=user2.sendermodel.pk)
        user1_receiver = ReceiverModel.objects.get(pk=user1.receivermodel.pk)
        user2_receiver = ReceiverModel.objects.get(pk=user2.receivermodel.pk)

        # Get the sender and receiver chats to each other
        user1_chats = ChatModel.objects.filter(sender=user1_sender, receiver=user2_receiver)
        user2_chats = ChatModel.objects.filter(sender=user2_sender, receiver=user1_receiver)

        # Put the chats in to `chats` list
        chats = [chat1 for chat1 in user1_chats]
        if not user1.get_username() == user2.get_username():
            # If the user1 and user2 are not the same, 
            # add the user2_chats and sort the `chats` 
            # with its pk using the `sort()` and 
            # `self.sort_pk()` method
            chats.extend([chat2 for chat2 in user2_chats])
            chats.sort(key=self.sort_pk)

        # Add the chats and user2 to context
        # for passing to template
        context = {
            'chats': chats,
            'user2': user2
        }
        return render(request, 'core/chat.html', context)
    
    def sort_pk(self, model):
        '''Returns `model.pk`. Can be use for sorting a queryset of Django Model'''
        return model.pk

user/views.py
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.contrib.auth.forms import UserCreationForm

class RegisterView(CreateView):
    model = User
    template_name = 'user/register.html'
    form_class = UserCreationForm

    def get_success_url(self):
        return reverse('user:login')

core/templates/core/chat.html
{% extends 'base.html' %}


{% block extra_head %}
    <style>
        #chat-container {
            /* Make the chat container scrollable */
            overflow: scroll;
            height: 280px;
        }
        .show {
            display: block;
        }
        .hide {
            display: none;
        }
    </style>
{% endblock extra_head %}
    
{% block content %}
    
    {% if user.username == user2.username %}
        <h3>Chat with yourself</h3>
    {% else %}
        <h3>Chat with {{ user2.username }}</h3>
    {% endif %}
        
    <div id="chat-container">
        {% for chat in chats %}
            <div class="chat">
                <p>
                    <b>{{ chat.sender.user.username }}:</b>
                    <span>{{ chat.text }}</span>
                </p>
                <p>{{ chat.log|date:'Y-m-d - h:i:s' }}</p>
            </div>
        {% endfor %}
    </div>
    <div>
        <small id="info" class="hide">Message input should not be empty.</small>
    </div>
    <input id="chat-input" />
    <button id="send-chat">Send</button>

    {{ user2.pk|json_script:'user2-pk' }}

    <script>
        // Setup user2 pk
        const user2_pk = JSON.parse(document.querySelector('#user2-pk').innerText);
        
        // Setup the websocket
        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + user2_pk
            + '/'
        );

        // When there is a message on websocket
        chatSocket.onmessage = (e) => {
            // Get and decode the message
            const message = JSON.parse(e.data)['chatmodel'];

            // Get the chat container and create chat div element for
            // the message
            const chatContainerEl = document.querySelector('#chat-container'),
                chatEl = document.createElement('div');
            chatEl.className = 'chat';

            // Setup elements for message
            const messageEl = document.createElement('p'),
                senderEl = document.createElement('b'),
                textEl = document.createElement('span'),
                logEl = document.createElement('p');
            
            // Put the message data to their corresponding element
            senderEl.innerText = message.sender_username + ': ';
            textEl.innerText = message.text;
            logEl.innerText = message.log;
            
            // Append the senderEl and textEl to messageEl
            messageEl.appendChild(senderEl);
            messageEl.appendChild(textEl);

            // Append the messageEl and logEl to chatEl
            chatEl.appendChild(messageEl);
            chatEl.appendChild(logEl);
            
            // Append the new message to chat container
            chatContainerEl.appendChild(chatEl);
        }

        // When enter has been clicked on #chat-input element
        document.querySelector('#chat-input').focus();
        document.querySelector('#chat-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#send-chat').click();
            }
        }

        document.querySelector('#send-chat').onclick = (e) => {
            const chatInput = document.querySelector('#chat-input');
            const chatInfo = document.querySelector('#info');
            if (!chatInput.value) {
                // Show the chat info when chat input is empty
                chatInfo.className = chatInfo.className.replace('hide', 'show');
                return
            }
            // Send message to websocket
            chatSocket.send(
                    JSON.stringify(
                        {
                            message: chatInput.value
                        }
                    )
            );
            // Make the chat input empty and hide the chat info
            chatInput.value = '';
            chatInfo.className = chatInfo.className.replace('show', 'hide');
        }
    </script>
{% endblock content %}
    

core/templates/core/home.html
{% extends 'base.html' %}

{% block content %}
    <h3>Chat users</h3>
    <ol>
        {% for object in users %}
            <li>
                <a href="{% url 'core:chat' object.pk %}">{{ object.username }}</a>
            </li>
        {% endfor %}
    </ol>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Channels Chat App</title>

    
    {% block extra_head %}{% endblock extra_head %}
</head>
<body>
    <h1>Django Channels Chat App</h1>
    
    {% if user.is_authenticated %}
        <h3>You are logged in as, {{ user.username }}</h3>
    {% endif %}
        
    <ul>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'core:home' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'user:logout' %}">Logout</a>
            </li>
        {% else %}
            <li>
                <a href="{% url 'user:login' %}">Login</a>
            </li>
            <li>
                <a href="{% url 'user:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
    {% block content %}{% endblock content %}
</body>
</html>

user/templates/user/login.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock content %}
    

user/templates/user/register.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock content %}
    